name: Create Release
on:
  push:
    tags:
    - '*'
env:
  BUILD_TYPE: Release
jobs:
  create-release:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [SF6]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDEVELOPER_MODE=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{matrix.target}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{matrix.target}}
          path: ${{github.workspace}}/build/bin/${{matrix.target}}/dinput8.dll
          if-no-files-found: error

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: ${{github.workspace}}/build/bin/${{matrix.target}}/dinput8.dll
          makeLatest: true
          allowUpdates: true
