name: Dev Release
on: [push, workflow_dispatch]
env:
  BUILD_TYPE: Release
jobs:
  dev-release:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [SF6]
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDEVELOPER_MODE=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{matrix.target}}

      - name: Upload artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: ${{matrix.target}}
          path: ${{github.workspace}}/build/bin/${{matrix.target}}/dinput8.dll
          if-no-files-found: error
    
  nightly-push:
    runs-on: windows-latest
    needs: dev-release
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427
        with:
          path: ${{github.workspace}}/artifacts

      - name: Set padded run number
        run: |
          $paddedRunNumber = "{0:D5}" -f ${{ github.run_number }}
          echo "RUN_NUMBER=$paddedRunNumber" >> $env:GITHUB_ENV
        shell: powershell

      - name: Create Release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
        with:
          repo: erik-perri/REFramework
          name: ${{format('REF Nightly {0} ({1})', env.RUN_NUMBER, github.sha)}}
          tag: ${{format('nightly-{0}-{1}', env.RUN_NUMBER, github.sha)}}
          artifacts: ${{github.workspace}}/artifacts/**/*.dll
          makeLatest: true
          bodyFile: ${{github.workspace}}/nightly-body.md
          allowUpdates: true

